---
title: "OrangeEconomy"
author: "Mahonry"
date: "22/4/2020"
output: html_document
knit: (function(inputFile, encoding) { 
      out_dir <- 'docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'index.html')) })
---

```{r}
orangeec <- read.csv("./data/orangeec.csv", header = TRUE, sep =",")
#data("orangeec")
summary(orangeec)
```
Parece que hay correlación entre aporte de economía naranja PIB y la tasa de desempleo
```{r}
pairs(orangeec[,0:6])
```
```{r}
library(ggplot2)
```
```{r}
ggplot()+geom_histogram(data=orangeec,aes(x=Internet.penetration...population), fill = "blue", color ="yellow", binwidth = 5) +  labs(x = "Penetración internet (%) población", y = "Cantidad de paises", title = "Penetración internet en países LATAM") + theme(panel.background = element_blank(), panel.grid.major =  element_blank(), panel.grid.minor = element_blank())
```
```{r}
library(dplyr)
```
```{r}
economy <- mean(orangeec$GDP.PC)
orangeec <- orangeec %>% mutate(Strong_economy = ifelse(GDP.PC<economy,"Por debajo promedio PIB per capita","Sobre promedio PIB per capita"))

ggplot(orangeec, aes(x=Strong_economy, y = Creat.Ind...GDP,fill=Strong_economy))+
  geom_boxplot(alpha = 0.4) + labs(x="Tipo de pais", y="Aporte economia naranja al PIB", title = "Aporte economia naranja en PIB paises LATAM con alto y bajo PIB per capita") + theme(panel.background = element_blank(), panel.grid.major =  element_blank(), panel.grid.minor = element_blank())
```


El Boxplot indica que los paises sobre el promedio en PIB per cápita tienen una dispersión mucho mas alta en cuanto a los aportes de la economía naranja al PIB del país.










